### ISSUE TITLE
FAIL: nothing to provision

### ISSUE THREAD

**Issue by F3R70** [remoteit/connectd#4]
I installed the service a month ago and ran smoothly with `ssh`. Today I installed `rdp` + `apt install xrdp` to remote desktop access (with successful connection). But after a temporary network drop the services were no longer available on the platform. Checking on the service status `systemctl status connectd.service` I got the next log showing the failure.

```
jun 25 03:00:12 raspberrypi systemd[1]: Started Remote tcp connection service.
jun 25 03:00:36 raspberrypi root[1058]: [connectd_start] Loop
jun 25 03:00:44 raspberrypi connectd_start[554]: /usr/bin/connectd_control: 777:local: bulk_identification_code
jun 25 03:00:44 raspberrypi root[1226]: [connectd_start]
jun 25 03:00:44 raspberrypi root[1227]: [connectd_start] Call bprovision
jun 25 03:00:44 raspberrypi root[1239]: [connectd_start] FAIL: nothing to provision
jun 25 03:00:44 raspberrypi root[1253]: /usr/bin/connectd_start started: FAIL: No active devices to start
jun 25 03:00:44 raspberrypi root[1256]: [connectd_start] exit
```

is there a way to prevent this from happening?

Kind regards

ps: I recovered the services by loggin into the device with other remote service and reinstalled `ssh` and `rdp`.

**Comment by dfleck99** [comment]
This happens because the startup script tries to start up services
which were configured using the interactive installer
(connectd_installer) vs. those set up using bulk or auto registration.

If no services have been configured using bulk or auto registration,
then you will see this "FAIL" message.  It is unnecessarily alarming.
There should only be concern if you are using bulk or auto
registration.

Presumably you are not using auto or bulk registration. To prevent
trying to start bulk/auto configured services edit

/usr/bin/connectd_start:

Find the line which calls do_provision and comment it out with a #
symbol at the beginning of the line.  See attached image.

Thanks,


Gary Worsham
Director of Applications Engineering
remot3.it, Inc.

**Comment by FernandoTorres** [comment]
Thanks for the response ... I'll try and report back

**Comment by lowerpower** [comment]
closing issue
